### ISSUE TITLE
Feature Request: Option to create cjs/amd/ems output

### ISSUE THREAD

**Issue by dak** [davidjamesstone/superviews.js#12]
It would be helpful to be able to create cjs, amd, and/or ems modules, as opposed to the default stand-alone that assumes certain globals exist.

For example, cjs output would be something like:
```js
var IncrementalDOM = require('incremental-dom'),
    elementOpen = IncrementalDOM.elementOpen,
    elementClose = IncrementalDOM.elementClose,
    elementVoid = IncrementalDOM.elementVoid,
    text = IncrementalDOM.text;

// hoisted values

module.exports = function description (data) {
elementOpen("div")
// ...
elementClose("div")
}
```

**Comment by davidjamesstone** [comment]
Thanks for this - I'd missed it.

There's been a request for this before.

I'm still not sure it belongs here. I created the superviewify transform for this for CJS purposes.

I wonder if it belongs in there rather than here in the main repository?

**Comment by dak** [comment]
I'll look into making a PR for superviewify as well as submitting a PR to gulp-supeviewsjs to use superviewify instead of superviews.js directly.

I'm not entirely sure of the advantage of the additional layer of abstraction though. With the growing popularity of modules in general in JS, and ES2015 modules in particular, having an option to output superviews.js as CJS, AMD, or ESM doesn't seem to be a huge stretch.

**Comment by davidjamesstone** [comment]
I've been thinking along the same line TBH.

Eventually it'll become es6 by default so the need for a separate transform package becomes obsolete.
