### ISSUE TITLE
Feature Request: Support for Conditional Attributes

### ISSUE THREAD

**Issue by dak** [davidjamesstone/superviews.js#15]
http://google.github.io/incremental-dom/#conditional-rendering/logic-in-attributes

Currently there's no way to have an attribute applied conditionally beyond using duplicate if blocks.  For example:
```html
<p class="{value === true ? 'active' : ''}">
```
will be compiled as:
```js
elementOpen("p", null, null, "class", "" + (value === true ? 'active' : '') + "")
```
Thus the value of the class is calculated prior to the script running and will always be the original value, rather than updating as the model changes.

It would be nice if attributes with logic would update on each patch to reflect changed states.

**Comment by davidjamesstone** [comment]
Hi there.

This is possible - see [here](https://github.com/davidjamesstone/superviews.js/issues/8)

Thanks

**Comment by dak** [comment]
Ah, I think this was a slightly different issue, but I just figured it out.  Interestingly, even though my model was using non-string values, I had to evaluate equality against a string.

So `value === 1` was always evaluating as false, even if value was indeed the number `1`, while `value === '1'` or `value == 1` was truthy.

**Comment by davidjamesstone** [comment]
Strange. I'd be interested to see the compiled incremental-dom that was causing that behaviour.
