### ISSUE TITLE
how to pass properties data?

### ISSUE THREAD

**Issue by alexsad** [davidjamesstone/superviews.js#23]
how i can pass the "prop" values to the template:
I'm doing this without success

```
<template name="UsingCustomTag" args="$data">
	<div>
		<h5>USING A CUSTOM TAG</h5>
		    <x-mytag text="test of test">		</x-mytag>
	</div>
</template>
```
I wait get this:
```
elementOpen('x-mytag', index, null,null ,
    'props', {
        text:'test of test'
      });
elementClose('x-mytag');
```
as this exemple:

https://github.com/google/incremental-dom/blob/master/demo/customelement.html

but the result is this:
```
var hoisted1 = ["text", "test of test"]
var __target
exports.UsingCustomTag = (function () {
  return function UsingCustomTag ($data) {
  elementOpen("div")
    elementOpen("h5")
      text("USING A CUSTOM TAG")
    elementClose("h5")
    elementOpen("x-mytag", "9c91f494-b337-4f73-8499-3c9b79606f53", hoisted1)
    elementClose("x-mytag")
  elementClose("div")
}
})()

```

**Comment by davidjamesstone** [comment]
How about this?

```
<template name="UsingCustomTag" args="$data">
	<div>
		<h5>USING A CUSTOM TAG</h5>
		    <x-mytag props="{$data.propsObj}"></x-mytag>
	</div>
</template>
```

**Comment by alexsad** [comment]
good day, it is good.
What do you think that when the User create "tags" with "-" attributes by nature are already "props", as with angular, aurelia and vue and other frameworks?
the standard of place "-" in "tags" custom, help in time to differentiate a normal html tag and created by the User.

**Comment by alexsad** [comment]
@davidjamesstone  I have a question , if i need pass two custom properties how can i do this?
```
<template name="UsingCustomTag" args="$data">
    <div>
        <h5>USING A CUSTOM TAG</h5>
            <x-mytag props="{text:$data.propsObj,maxpower:4546}"></x-mytag>
    </div>
</template>
```
?

**Comment by davidjamesstone** [comment]
Hi @alexsad, I'm not exactly sure I understand the question but have you seen [this](http://google.github.io/incremental-dom/#rendering-dom/attributes-and-properties)? 

In incremental-dom, values that are Objects or Functions are set as properties, with all others being set as attributes.

Therefore, the type of the data governs whether the value is set as a property or an attribute on the element.

Does this help?

**Comment by alexsad** [comment]
I think so, sorry for my explanation and english.
What i trying explain is that when we have two or more custom properties this can be in one variable.
So let my code try explain to me:

```
<template name="UsingCustomTag" args="$data">
    <div>
        <h5>USING A CUSTOM TAG</h5>
            <x-mytag props="{text:$data.propsObj,maxpower:4546}"></x-mytag>
    </div>
</template>
```
I hope that this will be translate to:
```
(function () {
return function UsingCustomTag ($data) {
  elementOpen("div");
    elementOpen("h5");
      text("USING A CUSTOM TAG");
    elementClose("h5");
    elementOpen("x-mytag", "9c91f494-b337-4f73-8499-3c9b79606f53", hoisted1, "props", {text:$data.propsObj,maxpower:4546});
    elementClose("x-mytag");
  elementClose("div");
}
})()
```

**Comment by davidjamesstone** [comment]
OK I see what you mean.
If you want a literal object you'll need to use double curly-braces:

```
<template name="UsingCustomTag" args="$data">
    <div>
        <h5>USING A CUSTOM TAG</h5>
        <x-mytag props="{{text:$data.propsObj, maxpower:4546}}"></x-mytag>
    </div>
</template>
```

All superviews does is output whatever is inside the first curly braces. For example, you could output an array if you wanted to:

```
<template name="UsingCustomTag" args="$data">
    <div>
        <h5>USING A CUSTOM TAG</h5>
        <x-mytag props="{[text:$data.propsObj, maxpower:4546]}"></x-mytag>
    </div>
</template>
```

Try it out [here](http://davidjamesstone.github.io/superviews.js/playground/)

**Comment by alexsad** [comment]
it's perfect to me!!! thanks!!!
