### ISSUE TITLE
where put a link to ferrugemjs in the documentation.

### ISSUE THREAD

**Issue by ferrugemjs** [davidjamesstone/superviews.js#25]
hello,
I have created a little reactive library called [FerrugemJS](https://www.npmjs.com/package/ferrugemjs) that uses superviews.js
Can I put a link to that in your documentation ?

**Comment by davidjamesstone** [comment]
Hi there - please do a PR.

Happy for it to go on the bottom of the main README.

Alternatively, link to a new ECOSYSTEM.md file.

I'm in the process of creating better documentation for superviews so the main README is undergoing much restructuring so maybe a new ECOSYSTEM.md would be better.

BTW - FerrugemJS looks very promising!

**Comment by ferrugemjs** [comment]
Thanks, i made a PR.
I'm waiting for your merge.
