### ISSUE TITLE
Inject HTML

### ISSUE THREAD

**Issue by robhicks** [davidjamesstone/superviews.js#35]
This is kind of related to [34](https://github.com/davidjamesstone/superviews.js/issues/34).

I'm looking for a way to inject safe HTML into an element, like:

angular 1: <ng-bind-html  ng-bind-html="expression"></ng-bind-html>
angular 2: <div [innerHTML]="theHtmlString"></div>

**Comment by davidjamesstone** [comment]
There's no support for setting HTML directly in Incremental DOM or superview.js.
The following could work using `currentElement` and `skip`.

```
<div skip>
  <script>
    const el = currentElement()
    el.innerHTML = data.myHtmlString
  </script>
</div>
```

**Comment by robhicks** [comment]
Thanks! I'll give it a try.

**Comment by robhicks** [comment]
@davidjamesstone I gave it a try. It compiled as you indicated. I have the data there and the element but calling el.innerHTML = data doesn't do anything.

Any suggestions?

**Comment by robhicks** [comment]
Adding skip to the element was the problem. I changed to this and it works:

```html
<div>
    <script>
      if (ctrl.html && ctrl.html !== '') {
        var el = currentElement();
        el.innerHTML = ctrl.html;
      }
      skip();
    </script>
  </div>
```

I got the idea for doing it this way from https://github.com/google/incremental-dom/issues/283
