### ISSUE TITLE
Setting innerHTML

### ISSUE THREAD

**Issue by zandaqo** [davidjamesstone/superviews.js#9]
Hi,

Is there a way to set element's innerHTML through the templates? Does Incremental DOM even allow this? I'm currently putting placeholders and manually populating them with content after rendering. In some cases, re-thinking architecture helps to avoid using innerHTML, but sometimes it's unavoidable, like inlining parsed markdown (which is an HTML string) or other cases of user generated content.

**Comment by davidjamesstone** [comment]
Hi.

No incremental-dom doesn't really support anything other than setting attributes or text content.

I use placeholder elements for this type of thing like you suggest.

Thanks

**Comment by zandaqo** [comment]
Thanks for clarifying this.

On a related note, is it possible to add placeholders in a loop? That is, I need to place varying number of placeholder elements with specified attributes. superviews don't accept my syntax and my attempts to do it through Incremental DOM give some weird errors, I'm wondering if it's even possible.

**Comment by davidjamesstone** [comment]
I'm can't see why it wouldn't work. I'm not at a computer at the moment.  Could you post sone examole code?

**Comment by zandaqo** [comment]
In templates I tried this:
```
<placeholder key="somekey" tag="div" data-index="{$index}" each="item in array"></placeholder>
```
but the output breaks template by failing to close the loop:
```
;(Array.isArray(array) ? exercise.data.text.sentenceCount : Object.keys(array)).forEach(function(item, $index) {
      elementPlaceholder("div", $index, null, "data-index", $index)
      // places the rest of the template here instead of closing the loop
```

Then I tried to fix the resulting template by manually closing the loop:
```
;(Array.isArray(array) ? exercise.data.text.sentenceCount : Object.keys(array)).forEach(function(item, $index) {
      elementPlaceholder("div", $index, null, "data-index", $index)
}, array)
```
From there idom complains about the key. I tried to generate keys dynamically replacing `$index` with `"key"+$index`, that just made it throw elsewhere complaining about some absent node. So, there I am now, wondering whether to go on debugging it, because idom doesn't seem too enthusiastic about the idea.

**Comment by davidjamesstone** [comment]
I see.

We could fix the close loop issue but if idom doesn't seem happy then maybe you're fighting a losing battle.

Other than having a wrapping element that does the loop and putting the placeholder inside that, I'm not sure.

I'll take a look this evening and get back to you.

**Comment by zandaqo** [comment]
> Other than having a wrapping element that does the loop and putting the placeholder inside that, I'm not sure.

It works:
```
      <span each="item in array">
        <placeholder key="someKey" tag="div" data-index="{$index}"></placeholder>
      </span>
```
This construction compiles into this:
```
      ;(Array.isArray(array) ? array : Object.keys(array)).forEach(function(item, $index) {
        elementOpen("span", $index)
          elementPlaceholder("span", "someKey", hoisted5, "data-index", $index)
        elementClose("span")
      }, array)
```

And idom seems to work with it. Interestingly, when I remove opening and closing calls inside this, idom begins to mess with the $index starting it from 1 rather than zero. 

I guess I'll go with the wrapping element for now. It would be nice to do without it, but that's probably more of an idom's issue than superviews. Thank you!
